-- https://brigades.opendatanetwork.com/api/views/seai-775i/rows.csv?accessType=DOWNLOAD
-- sed "s/\%//g" durham_compass_data.csv | sed "s/\\$//g" > durham_compass_data_stripped.csv

DROP TABLE IF EXISTS durham_blockgroup_data;
CREATE TABLE durham_blockgroup_data (
  object_id SMALLINT,
  count_id SMALLINT,
  census_tract VARCHAR(10),
  blockgroup SMALLINT,
  geo_id BIGINT,
  blockgroup_name VARCHAR(55),
  unused_string_1 VARCHAR(55),
  unused_string_2 VARCHAR(55),
  unused_string_3 VARCHAR(255),
  unused_string_4 VARCHAR(55),
  unused_string_5 VARCHAR(55),
  PDENS DECIMAL(12, 2),
	SWTORD DECIMAL(12, 2),
	V_PER_SQMI DECIMAL(12, 2),
	P_PER_SQMI DECIMAL(12, 2),
	D_PER_SQMI DECIMAL(12, 2),
	AREA_SQMI DECIMAL(12, 2),
	LUDIVERSE DECIMAL(12, 2),
	R_AVGYR DECIMAL(12, 2),
	PCTSSI DECIMAL(12, 2),
	population INTEGER,
	pct_latino DECIMAL(6, 2),
	pct_white DECIMAL(6, 2),
	pct_black DECIMAL(6, 2),
	pct_asian DECIMAL(6, 2),
	pct_other_race DECIMAL(6, 2),
	RE_DIVERSE DECIMAL(12, 2),
	median_age DECIMAL(12, 2),
	pct_under_18 DECIMAL(6, 2),
	pct_65_up DECIMAL(6, 2),
	median_household_income DECIMAL(12, 2),
	PCI DECIMAL(12, 2),
	PCTRENT DECIMAL(12, 2),
	PCTUNFRENT DECIMAL(12, 2),
	PCTUNFOWN DECIMAL(12, 2),
	PCTC30 DECIMAL(12, 2),
	PCTDRALONE DECIMAL(12, 2),
	PCTBIKEWK DECIMAL(12, 2),
	PCTWLKWK DECIMAL(12, 2),
	PCTWRKHM DECIMAL(12, 2),
	PCTR_GRCR DECIMAL(12, 2),
	PCTR_PHARM DECIMAL(12, 2),
	PCTR_BANK DECIMAL(12, 2),
	PCTR_BUSST DECIMAL(12, 2),
	DAYTRIPS DECIMAL(12, 2),
	EVETRIPS DECIMAL(12, 2),
	TREE_PCT DECIMAL(12, 2),
	IMP_PCT DECIMAL(12, 2),
	id DECIMAL(12, 2),
	AREA_SQMI_ DECIMAL(12, 2),
	CVALPSM_12 DECIMAL(12, 2),
	RVALPSM_12 DECIMAL(12, 2),
	ACODEV_12 DECIMAL(12, 2),
	WCODEV_12 DECIMAL(12, 2),
	RCODEV_12 DECIMAL(12, 2));


COPY durham_blockgroup_data from '/Users/dave/repos/durham-openvr/durham_compass_data_stripped.csv' with csv delimiter ',' header;